CBVDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls', namespace="first")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordResetDoneView

app_name = "accounts"
urlpatterns = [
    path('login/', views.UserLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password_reset/', views.PasswordReset.as_view(), name="password_reset"),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name="password_reset_done"),
    path("confirm/<uidb64>/<token>/", views.PasswordResetConfirm.as_view(), name="password_reset_confirm"),
    path("password_reset/complete/", views.PasswordResetComplete.as_view(), name="password_reset_complete")
]

first/urls.py
from django.urls import path
from . import views

app_name = "first"
urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('todo_create/', views.TodoCreate.as_view(), name="todo_create"),
    path('detail_todo/<slug:slug>/', views.DetailTodo.as_view(), name="detail_todo"),
    path('delete/<int:pk>/', views.DeleteTodo.as_view(), name="delete_todo"),
    path('edit_todo/<int:pk>',views.EditTodo.as_view(), name="edit_todo"),

]

accounts/models.py
from django.db import models

# Create your models here.

first/models.py
from django.db import models


class Todo(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, related_name="tcomment")
    name = models.CharField(max_length=50)
    body = models.TextField()

first/forms.py
from django import forms
from .models import Comment


class TodoCreateForm(forms.Form):
    title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': "form-control"}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "body",)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


class UserLogin(LoginView):
    template_name = "accounts/login.html"


class PasswordReset(PasswordResetView):
    template_name = "accounts/password_reset_form.html"
    success_url = reverse_lazy("accounts:password_reset_done")
    email_template_name = "accounts/password_reset_email.html"


class PasswordResetDone(PasswordResetDoneView):
    template_name = "accounts/reset_done.html"


class PasswordResetConfirm(PasswordResetConfirmView):
    template_name = "accounts/password_reset_confirm.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"

first/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from .models import Todo
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.contrib import messages
from .forms import CommentForm
from .models import Comment


class Home(ListView):
    template_name = "first/home.html"
    model = Todo
    context_object_name = "todos"
    ordering = ("-created",)


class DetailTodo(LoginRequiredMixin, FormMixin, DetailView):
    template_name = "first/detail_todo.html"
    slug_field = "slug"
    slug_url_kwarg = "slug"
    model = Todo
    form_class = CommentForm

    def get_success_url(self):
        return reverse("first:detail_todo", kwargs={'slug': self.object.slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            comment = Comment(todo=self.object, name=form.cleaned_data['name'], body=form.cleaned_data['body'])
            comment.save()
        return super().form_valid(form)


# class TodoCreate(FormView):
#     form_class = TodoCreateForm
#     template_name = "first/todo_create.html"
#     success_url = reverse_lazy("first:home")
#
#     def form_valid(self, form):
#         self.create_todo(form.cleaned_data)
#         return super().form_valid(form)
#
#     def create_todo(self, data):
#         todo = Todo(title=data['title'], slug=slugify(data['title']))
#         todo.save()
#         messages.success(self.request, "your todo added successfully", "success")

class TodoCreate(CreateView):
    model = Todo
    fields = ('title',)
    template_name = "first/todo_create.html"
    success_url = reverse_lazy("first:home")

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.slug = slugify(form.cleaned_data['title'])
        todo.save()
        messages.success(self.request, "your todo added successfully", "success")
        return super().form_valid(form)


class DeleteTodo(DeleteView):
    template_name = "first/delete_todo.html"
    model = Todo
    success_url = reverse_lazy("first:home")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "todo deleted successfully", "danger")
        return super(DeleteTodo, self).delete(request, *args, **kwargs)


class EditTodo(UpdateView):
    model = Todo
    fields = ('title',)
    template_name = "first/edit_todo.html"
    success_url = reverse_lazy("first:home")

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-primary">

    </form>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
    <p>password reset successfully!</p>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
    {% if validlink %}
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Change" class="btn btn-primary">
        </form>
    {% else %}
        <p>this link is not valid, Try again</p>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
    <p>enter your email to send reset password email:</p>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
{% endblock content %}

accounts/templates/accounts/reset_done.html
{% extends 'base.html' %}
{% block content %}
    <p>Email Sent!check your email</p>
{% endblock %}

first/templates/first/delete_todo.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock content %}

first/templates/first/detail_todo.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-start m-2">
        <a class="btn btn-danger text-start"
           href="{% url "first:delete_todo" todo.id %}">Delete</a>
        <a class="btn btn-warning text-start"
           href="{% url "first:edit_todo" todo.id %}">Edit</a>
    </div>
    <div class="card">
        <h2 class="card-header">ID:{{ todo.id }}</h2>
        <p class="card-body">{{ todo.title }}</p>
        <small class="card-footer">{{ todo.created }}</small>
    </div>
    <div class="m-5">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sent" class="btn btn-primary">
        </form>

    </div>
    <hr>
    {% for commnet in todo.tcomment.all %}
        {{ commnet.name }}
        {{ commnet.body }}
        <br>
        <hr>
    {% endfor %}

{% endblock content %}

first/templates/first/edit_todo.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
{% endblock content %}

first/templates/first/hello.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% for todo in todos %}
            <a href="{% url "first:detail_todo" todo.slug %}">{{ todo }}</a>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

first/templates/first/home.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div class="text-start"><a class="btn btn-success" href="{% url "first:todo_create" %}">Create Todo</a></div>

        {% for todo in todos %}
            <a href="{% url "first:detail_todo" todo.slug %}">{{ todo }}</a>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

first/templates/first/todo_create.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" class="btn btn-primary">
    </form>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
{% include "inc/navbar.html" %}
<div class="container-fluid text-sm-center p-5 bg-light">
    <div class="container">
        {% include "inc/messages.html" %}
        {% block content %}

        {% endblock content %}
    </div>
</div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link" href="{% url "first:home" %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url "accounts:logout" %}">Logout</a>
            {% else %}
                <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>